export const READ_CART_PRODUCTS = 'READ_CART_PRODUCTS'
export const READ_CART_PRODUCTS_SUCCESS = 'READ_CART_PRODUCTS_SUCCESS'
export const READ_CART_PRODUCTS_ERROR = 'READ_CART_PRODUCTS_ERROR'

export const SEND_ORDER = 'SEND_ORDER'
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS'
export const SEND_ORDER_ERROR = 'SEND_ORDER_ERROR'

export const CLEAR_CART = 'CLEAR_CART'

export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'