export const READ_PRODUCTS = 'READ_PRODUCTS'
export const READ_PRODUCTS_REQUEST = 'READ_PRODUCTS_REQUEST'
export const READ_PRODUCTS_SUCCESS = 'READ_PRODUCTS_SUCCESS'
export const READ_PRODUCTS_ERROR = 'READ_PRODUCTS_ERROR'
