export const READ_PRODUCT_DETAILS = 'READ_PRODUCT_DETAILS'
export const READ_PRODUCT_DETAILS_REQUEST = 'READ_PRODUCT_DETAILS_REQUEST'
export const READ_PRODUCT_DETAILS_SUCCESS = 'READ_PRODUCT_DETAILS_SUCCESS'
export const READ_PRODUCT_DETAILS_ERROR = 'READ_PRODUCT_DETAILS_ERROR'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const BUY_PRODUCT = 'BUY_PRODUCT'
export const BUY_PRODUCT_REQUEST = 'BUY_PRODUCT_REQUEST'
export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS'
export const BUY_PRODUCT_ERROR = 'BUY_PRODUCT_ERROR'