export const READ_PRODUCT = 'READ_PRODUCT'
export const READ_PRODUCT_SUCCESS = 'READ_PRODUCT_SUCCESS'
export const READ_PRODUCT_ERROR = 'READ_PRODUCT_ERROR'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const BUY_PRODUCT = 'BUY_PRODUCT'
export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS'
export const BUY_PRODUCT_ERROR = 'BUY_PRODUCT_ERROR'