export const READ_PRODUCT = 'READ_PRODUCT'
export const READ_PRODUCT_SUCCESS = 'READ_PRODUCT_SUCCESS'
export const READ_PRODUCT_ERROR = 'READ_PRODUCT_ERROR'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const LOCAL_EDIT_PRODUCT = 'LOCAL_EDIT_PRODUCT'

export const UPDATE_ERRORS = 'UPDATE_ERRORS'